My first Portfolio (mobile first)
fdezcaminero/superFigmaPortfolio pull request #1
Opened 2022-10-26 22:16 UTC by fdezcaminero

* Brilliantly crafted Navbar
* Descriptive headline section
* Amazing decoration

2022-10-26 22:56 UTC, mckent05 requested changes
Hi @fdezcaminero,

# STATUS: CHANGES REQUIRED ♻️ ♻️  

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/198153775-95264be2-d700-4593-9118-665372490cd9.gif)

## Highlights
- All linter checks are passing ✔️ 
- Descriptive commit messages 👍 👍 
- Your project looks good 👏 👏 


## Required Changes ♻️
- According to project requirements, in order to make your project look good across all mobile screen sizes, I'd suggest you make your portfolio responsive, please fix this 😄 😄 
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 22:56 UTC, mckent05 commented on index.html
> +        </footer>
- Great job done so far, for aesthetic reasons I'd advise that you add this image in CSS using the `background-image` property, please fix this 🙏.
- There are also some little differences between your site and the design in the figma template. The background image in this section occupies the entire width of the page. Please fix this issue in your site 👍 👍 

Your project 👇:
<img width="171" alt="jose" src="https://user-images.githubusercontent.com/73607512/198152422-db21d793-993d-4382-800b-39bdc5814011.PNG">

Figma template:
<img width="171" alt="jose" src="https://user-images.githubusercontent.com/73607512/198152455-dd08b14d-e5b5-46d8-b771-163f4766ec53.PNG">

2022-10-26 22:56 UTC, mckent05 commented on index.html
> +        </footer>
- Great job done so far, for aesthetic reasons I'd advise that you add this image in CSS using the `background-image` property, please fix this 🙏.
- There are also some little differences between your site and the design in the figma template. The background image in this section occupies the entire width of the page. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏. Please fix this issue in your site 👍 👍 

Your project 👇:
<img width="171" alt="jose" src="https://user-images.githubusercontent.com/73607512/198152422-db21d793-993d-4382-800b-39bdc5814011.PNG">

Figma template:
<img width="266" alt="jose figma" src="https://user-images.githubusercontent.com/73607512/198152602-d3d0c41b-81ce-4aaa-9591-26be68938d04.PNG">

2022-10-26 22:56 UTC, mckent05 commented on index.html
> +        <button>Start collaboration</button>
- There are a few differences between your design and the Figma design template, this button takes up more width in the design template and is also aligned in the center. Please try to fix this 🙏 . Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your Project 👇:
<img width="156" alt="jose button" src="https://user-images.githubusercontent.com/73607512/198153441-eb4e0e65-e3b4-4309-92cd-1440bdb0c0cf.PNG">

Figma template:
<img width="254" alt="jose button figma" src="https://user-images.githubusercontent.com/73607512/198153554-9ad27ada-075c-4c93-940f-917c23856d15.PNG">

2022-10-27 22:28 UTC, fdezcaminero commented on index.html
> +        <button>Start collaboration</button>
@mckent05 I'm sorry, but they seem exactly the same. 288px. Did you zoom in accidentally?

2022-10-27 22:39 UTC, fdezcaminero commented on index.html
> +        </footer>
@mckent05 Hey, I've been trying to make the background-image full width but it has been very difficult. It's very easy with img but very difficult with background-image. I've asked here at Microverse, I've asked in Stack Overflow. Still no answer. Because the container has a constant height so it doesn't resize easily. Here's my code at the moment:

.footerDeco {
  background-image: url(../resources/image_geometry_2.svg);
  background-repeat: no-repeat;
  height: 160px;
  background-size: cover;
}

When the image resizes to fit the width the height remains the same. If I make the height any larger then it doesn't work when the screen becomes smaller. It doesn't resize to fit the smaller screen.

Any advice?

2022-10-28 14:59 UTC, medaminedev66 commented on index.html
> +        <button>Start collaboration</button>
Hi @fdezcaminero,

As a result of the request for a second opinion, I'm currently reviewing your pull request.

2022-10-28 15:20 UTC, fdezcaminero commented on index.html
> +        <button>Start collaboration</button>
@medaminedev66 Thanks! Remember, I'm not saying that the requests of @mckent05 are incorrect. It's just that I bumped into a problem that seems very tricky to me. Maybe he himself did not anticipate how tricky it was. I posted at Stack Overflow yesterday and still no one's answer has worked:

https://stackoverflow.com/questions/74228659/give-a-resizable-background-image-a-full-width

2022-10-28 15:20 UTC, medaminedev66 commented
Hello @fdezcaminero 👋,

_This is an additional review as a result of the second opinion request._

The previous reviewer mentioned great points. Let me help you with fixing those issues.

Our design should be flexible and fit all mobile screen sizes (360px, 420px ...), about the button I recommend using `width:100%` instead of a fixed width so that your control fits all mobile screen sizes. 

For the background image, I recommend implementing the following instructions:

```css
.footerDeco {
    background-image: url(../resources/image_geometry_2.svg);
    background-size: cover;
    background-repeat: no-repeat;
    width: 100%;
    height: 0;
    padding-top: 50%; /* (img-height / img-width * container-width) */
                /* (160 / 320 * 100) */
}
```
By implementing that, your project will be complete

Keep rocking 🚀

2022-10-28 17:37 UTC, aimalamiri approved these changes
Hi @fdezcaminero, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![ApprovedDavieGIF](https://user-images.githubusercontent.com/34779928/191333120-c0c2ce83-28e1-4dbc-aac1-09e467f7a8bd.gif)


## Highlights

- The header section is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 17:48 UTC, merged